export const products = [
    {
        id: 1,
        name: "عسل السدر الجبلي",
        description: "عسل سدر طبيعي 100% من جبال السروات، يتميز بلونه الداكن وطعمه الفريد",
        price: 149,
        oldPrice: 179,
        category: "sider",
        image: "images/product-3.jpg",
        rating: 4.5,
        stock: 15,
        badge: "الأكثر مبيعاً"
    },
    {
        id: 2,
        name: "عسل المانوكا النيوزيلندي",
        description: "عسل مانوكا درجة MGO 400+، مضاد طبيعي للبكتيريا والالتهابات",
        price: 299,
        oldPrice: 349,
        category: "manuka",
        image: "images/product-4.jpg",
        rating: 5,
        stock: 8,
        badge: "مميز"
    },
    {
        id: 3,
        name: "عسل الزهور البري",
        description: "خليط من أعسال الزهور البرية الطبيعية، طعم منعش ورائحة زكية",
        price: 99,
        oldPrice: null,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4,
        stock: 25,
        badge: null
    },
    {
        id: 4,
        name: "عسل البرسيم الأبيض",
        description: "عسل برسيم فاخر بلون فاتح وطعم لذيذ، مثالي للتحلية اليومية",
        price: 119,
        oldPrice: 139,
        category: "clover",
        image: "images/product-4.jpg",
        rating: 4.5,
        stock: 20,
        badge: "عرض خاص"
    },
    {
        id: 5,
        name: "عسل السدر العضوي",
        description: "عسل سدر عضوي معتمد، خالي من المبيدات والمواد الكيميائية",
        price: 199,
        oldPrice: 229,
        category: "sider",
        image: "images/product-3.jpg",
        rating: 4.8,
        stock: 12,
        badge: "عضوي"
    },
    {
        id: 6,
        name: "عسل الكينا العلاجي",
        description: "عسل الكينا المستخدم في العلاجات الطبيعية للسعال والجهاز التنفسي",
        price: 159,
        oldPrice: 189,
        category: "flowers",
        image: "images/product-4.jpg",
        rating: 4.3,
        stock: 18,
        badge: null
    },
    {
        id: 7,
        name: "عسل الأكاسيا الصافي",
        description: "عسل أكاسيا نقي، يتميز بلونه الفاتح جداً وطعمه الخفيف",
        price: 139,
        oldPrice: null,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4.6,
        stock: 30,
        badge: "جديد"
    },
    {
        id: 8,
        name: "عسل الغابة السوداء",
        description: "عسل داكن اللون غني بالمعادن، طعم قوي ومميز",
        price: 189,
        oldPrice: 219,
        category: "flowers",
        image: "images/product-4.jpg",
        rating: 4.7,
        stock: 10,
        badge: "فاخر"
    },
    {
        id: 9,
        name: "عسل المانوكا MGO 100+",
        description: "عسل مانوكا للاستخدام اليومي، يعزز المناعة والصحة العامة",
        price: 199,
        oldPrice: null,
        category: "manuka",
        image: "images/product-3.jpg",
        rating: 4.4,
        stock: 22,
        badge: null
    },
    {
        id: 10,
        name: "عسل المانوكا MGO 850+",
        description: "أقوى أنواع عسل المانوكا، خصائص علاجية فائقة",
        price: 599,
        oldPrice: 699,
        category: "manuka",
        image: "images/product-4.jpg",
        rating: 5,
        stock: 5,
        badge: "نادر"
    },
    {
        id: 11,
        name: "عسل الحمضيات",
        description: "عسل مستخلص من أزهار الحمضيات، طعم حامضي منعش",
        price: 89,
        oldPrice: 109,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4.2,
        stock: 40,
        badge: "عرض"
    },
    {
        id: 12,
        name: "عسل اللافندر",
        description: "عسل برائحة اللافندر الزكية، مهدئ للأعصاب",
        price: 129,
        oldPrice: null,
        category: "flowers",
        image: "images/product-4.jpg",
        rating: 4.5,
        stock: 15,
        badge: null
    },
    {
        id: 13,
        name: "شمع العسل الطبيعي",
        description: "قطعة من شمع العسل الطبيعي الطازج، تجربة مضغ فريدة",
        price: 79,
        oldPrice: null,
        category: "gifts",
        image: "images/product-3.jpg",
        rating: 4.9,
        stock: 25,
        badge: "طبيعي"
    },
    {
        id: 14,
        name: "صندوق هدايا العسل الفاخر",
        description: "تشكيلة من 3 أنواع عسل فاخر في صندوق خشبي أنيق",
        price: 399,
        oldPrice: 499,
        category: "gifts",
        image: "images/product-4.jpg",
        rating: 5,
        stock: 10,
        badge: "هدية"
    },
    {
        id: 15,
        name: "عسل السمر",
        description: "عسل سمر يمني أصلي، طعم قوي وفوائد صحية جمة",
        price: 249,
        oldPrice: 299,
        category: "sider",
        image: "images/product-3.jpg",
        rating: 4.8,
        stock: 12,
        badge: null
    },
    {
        id: 16,
        name: "عسل الطلح",
        description: "عسل طلح بري، مفيد للجهاز الهضمي",
        price: 169,
        oldPrice: 199,
        category: "sider",
        image: "images/product-4.jpg",
        rating: 4.4,
        stock: 18,
        badge: null
    },
    {
        id: 17,
        name: "ملعقة عسل خشبية",
        description: "ملعقة مصممة خصيصاً للعسل من خشب الزيتون",
        price: 25,
        oldPrice: null,
        category: "gifts",
        image: "images/product-3.jpg",
        rating: 4.5,
        stock: 100,
        badge: null
    },
    {
        id: 18,
        name: "عسل الزعتر",
        description: "عسل جبلي من أزهار الزعتر، مفيد للسعال",
        price: 145,
        oldPrice: null,
        category: "flowers",
        image: "images/product-4.jpg",
        rating: 4.6,
        stock: 20,
        badge: null
    },
    {
        id: 19,
        name: "عسل حبة البركة",
        description: "عسل ممزوج بخلاصة حبة البركة لتعزيز المناعة",
        price: 115,
        oldPrice: 135,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4.3,
        stock: 30,
        badge: "صحي"
    },
    {
        id: 20,
        name: "مجموعة تذوق العسل",
        description: "5 عبوات صغيرة لتذوق أنواع مختلفة من العسل",
        price: 89,
        oldPrice: null,
        category: "gifts",
        image: "images/product-4.jpg",
        rating: 4.7,
        stock: 50,
        badge: "تجربة"
    }
];
