export const products = [
    {
        id: 1,
        name: "عسل السدر الجبلي",
        description: "عسل سدر طبيعي 100% من جبال السروات، يتميز بلونه الداكن وطعمه الفريد",
        price: 149,
        oldPrice: 179,
        category: "sider",
        image: "images/product-1.jpg",
        rating: 4.5,
        stock: 15,
        badge: "الأكثر مبيعاً"
    },
    {
        id: 2,
        name: "عسل المانوكا النيوزيلندي",
        description: "عسل مانوكا درجة MGO 400+، مضاد طبيعي للبكتيريا والالتهابات",
        price: 299,
        oldPrice: 349,
        category: "manuka",
        image: "images/product-2.jpg",
        rating: 5,
        stock: 8,
        badge: "مميز"
    },
    {
        id: 3,
        name: "عسل الزهور البري",
        description: "خليط من أعسال الزهور البرية الطبيعية، طعم منعش ورائحة زكية",
        price: 99,
        oldPrice: null,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4,
        stock: 25,
        badge: null
    },
    {
        id: 4,
        name: "عسل البرسيم الأبيض",
        description: "عسل برسيم فاخر بلون فاتح وطعم لذيذ، مثالي للتحلية اليومية",
        price: 119,
        oldPrice: 139,
        category: "clover",
        image: "images/product-4.jpg",
        rating: 4.5,
        stock: 20,
        badge: "عرض خاص"
    },
    {
        id: 5,
        name: "عسل السدر العضوي",
        description: "عسل سدر عضوي معتمد، خالي من المبيدات والمواد الكيميائية",
        price: 199,
        oldPrice: 229,
        category: "sider",
        image: "images/product-5.jpg",
        rating: 4.8,
        stock: 12,
        badge: "عضوي"
    },
    {
        id: 6,
        name: "عسل الكينا العلاجي",
        description: "عسل الكينا المستخدم في العلاجات الطبيعية للسعال والجهاز التنفسي",
        price: 159,
        oldPrice: 189,
        category: "flowers",
        image: "images/product-6.jpg",
        rating: 4.3,
        stock: 18,
        badge: null
    },
    {
        id: 7,
        name: "عسل الأكاسيا الصافي",
        description: "عسل أكاسيا نقي، يتميز بلونه الفاتح جداً وطعمه الخفيف",
        price: 139,
        oldPrice: null,
        category: "flowers",
        image: "images/product-7.jpg",
        rating: 4.6,
        stock: 30,
        badge: "جديد"
    },
    {
        id: 8,
        name: "عسل الغابة السوداء",
        description: "عسل داكن اللون غني بالمعادن، طعم قوي ومميز",
        price: 189,
        oldPrice: 219,
        category: "flowers",
        image: "images/product-8.jpg",
        rating: 4.7,
        stock: 10,
        badge: "فاخر"
    },
    {
        id: 9,
        name: "عسل المانوكا MGO 100+",
        description: "عسل مانوكا للاستخدام اليومي، يعزز المناعة والصحة العامة",
        price: 199,
        oldPrice: null,
        category: "manuka",
        image: "images/product-9.jpg",
        rating: 4.4,
        stock: 22,
        badge: null
    },
    {
        id: 10,
        name: "عسل المانوكا MGO 850+",
        description: "أقوى أنواع عسل المانوكا، خصائص علاجية فائقة",
        price: 599,
        oldPrice: 699,
        category: "manuka",
        image: "images/product-10.jpg",
        rating: 5,
        stock: 5,
        badge: "نادر"
    },
    {
        id: 11,
        name: "عسل الحمضيات",
        description: "عسل مستخلص من أزهار الحمضيات، طعم حامضي منعش",
        price: 89,
        oldPrice: 109,
        category: "flowers",
        image: "images/product-11.jpg",
        rating: 4.2,
        stock: 40,
        badge: "عرض"
    },
    {
        id: 12,
        name: "عسل اللافندر",
        description: "عسل برائحة اللافندر الزكية، مهدئ للأعصاب",
        price: 129,
        oldPrice: null,
        category: "flowers",
        image: "images/product-1.jpg",
        rating: 4.5,
        stock: 15,
        badge: null
    },
    {
        id: 13,
        name: "شمع العسل الطبيعي",
        description: "قطعة من شمع العسل الطبيعي الطازج، تجربة مضغ فريدة",
        price: 79,
        oldPrice: null,
        category: "gifts",
        image: "images/product-2.jpg",
        rating: 4.9,
        stock: 25,
        badge: "طبيعي"
    },
    {
        id: 14,
        name: "صندوق هدايا العسل الفاخر",
        description: "تشكيلة من 3 أنواع عسل فاخر في صندوق خشبي أنيق",
        price: 399,
        oldPrice: 499,
        category: "gifts",
        image: "images/product-3.jpg",
        rating: 5,
        stock: 10,
        badge: "هدية"
    },
    {
        id: 15,
        name: "عسل السمر",
        description: "عسل سمر يمني أصلي، طعم قوي وفوائد صحية جمة",
        price: 249,
        oldPrice: 299,
        category: "sider",
        image: "images/product-4.jpg",
        rating: 4.8,
        stock: 12,
        badge: null
    },
    {
        id: 16,
        name: "عسل الطلح",
        description: "عسل طلح بري، مفيد للجهاز الهضمي",
        price: 169,
        oldPrice: 199,
        category: "sider",
        image: "images/product-5.jpg",
        rating: 4.4,
        stock: 18,
        badge: null
    },
    {
        id: 17,
        name: "ملعقة عسل خشبية",
        description: "ملعقة مصممة خصيصاً للعسل من خشب الزيتون",
        price: 25,
        oldPrice: null,
        category: "gifts",
        image: "images/product-6.jpg",
        rating: 4.5,
        stock: 100,
        badge: null
    },
    {
        id: 18,
        name: "عسل الزعتر",
        description: "عسل جبلي من أزهار الزعتر، مفيد للسعال",
        price: 145,
        oldPrice: null,
        category: "flowers",
        image: "images/product-7.jpg",
        rating: 4.6,
        stock: 20,
        badge: null
    },
    {
        id: 19,
        name: "عسل حبة البركة",
        description: "عسل ممزوج بخلاصة حبة البركة لتعزيز المناعة",
        price: 115,
        oldPrice: 135,
        category: "flowers",
        image: "images/product-8.jpg",
        rating: 4.3,
        stock: 30,
        badge: "صحي"
    },
    {
        id: 20,
        name: "مجموعة تذوق العسل",
        description: "5 عبوات صغيرة لتذوق أنواع مختلفة من العسل",
        price: 89,
        oldPrice: null,
        category: "gifts",
        image: "images/product-9.jpg",
        rating: 4.7,
        stock: 50,
        badge: "تجربة"
    }
,
    {
        id: 21,
        name: "عسل الطلح الصحي",
        description: "وصف توضيحي للمنتج عسل الطلح الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 452,
        oldPrice: 529,
        category: "gifts",
        image: "images/product-10.jpg",
        rating: 4.1,
        stock: 82,
        badge: 'مميز'
    },
    {
        id: 22,
        name: "عسل البرسيم النقي",
        description: "وصف توضيحي للمنتج عسل البرسيم النقي، يتميز بجودة عالية وطعم رائع.",
        price: 122,
        oldPrice: 179,
        category: "gifts",
        image: "images/product-11.jpg",
        rating: 4.7,
        stock: 68,
        badge: 'مميز'
    },
    {
        id: 23,
        name: "عسل الكينا البري",
        description: "وصف توضيحي للمنتج عسل الكينا البري، يتميز بجودة عالية وطعم رائع.",
        price: 146,
        oldPrice: 218,
        category: "flowers",
        image: "images/product-1.jpg",
        rating: 4.4,
        stock: 60,
        badge: 'مميز'
    },
    {
        id: 24,
        name: "عسل السدر الصحي",
        description: "وصف توضيحي للمنتج عسل السدر الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 195,
        oldPrice: 231,
        category: "manuka",
        image: "images/product-2.jpg",
        rating: 3.8,
        stock: 62,
        badge: 'عرض'
    },
    {
        id: 25,
        name: "عسل الطلح النادر",
        description: "وصف توضيحي للمنتج عسل الطلح النادر، يتميز بجودة عالية وطعم رائع.",
        price: 273,
        oldPrice: null,
        category: "clover",
        image: "images/product-3.jpg",
        rating: 4.8,
        stock: 72,
        badge: 'مميز'
    },
    {
        id: 26,
        name: "شمع العسل الملكي",
        description: "وصف توضيحي للمنتج شمع العسل الملكي، يتميز بجودة عالية وطعم رائع.",
        price: 187,
        oldPrice: null,
        category: "flowers",
        image: "images/product-4.jpg",
        rating: 4.4,
        stock: 4,
        badge: 'مميز'
    },
    {
        id: 27,
        name: "عسل السدر الجبلي",
        description: "وصف توضيحي للمنتج عسل السدر الجبلي، يتميز بجودة عالية وطعم رائع.",
        price: 82,
        oldPrice: null,
        category: "gifts",
        image: "images/product-5.jpg",
        rating: 3.8,
        stock: 43,
        badge: 'جديد'
    },
    {
        id: 28,
        name: "عسل الطلح البري",
        description: "وصف توضيحي للمنتج عسل الطلح البري، يتميز بجودة عالية وطعم رائع.",
        price: 197,
        oldPrice: null,
        category: "gifts",
        image: "images/product-6.jpg",
        rating: 4.6,
        stock: 7,
        badge: 'عرض'
    },
    {
        id: 29,
        name: "عسل السدر المميز",
        description: "وصف توضيحي للمنتج عسل السدر المميز، يتميز بجودة عالية وطعم رائع.",
        price: 247,
        oldPrice: null,
        category: "clover",
        image: "images/product-7.jpg",
        rating: 4.1,
        stock: 66,
        badge: 'جديد'
    },
    {
        id: 30,
        name: "عسل الحمضيات الملكي",
        description: "وصف توضيحي للمنتج عسل الحمضيات الملكي، يتميز بجودة عالية وطعم رائع.",
        price: 488,
        oldPrice: null,
        category: "gifts",
        image: "images/product-8.jpg",
        rating: 5.0,
        stock: 78,
        badge: null
    },
    {
        id: 31,
        name: "عسل الطلح العضوي",
        description: "وصف توضيحي للمنتج عسل الطلح العضوي، يتميز بجودة عالية وطعم رائع.",
        price: 112,
        oldPrice: null,
        category: "gifts",
        image: "images/product-9.jpg",
        rating: 4.5,
        stock: 66,
        badge: 'عرض'
    },
    {
        id: 32,
        name: "غذاء ملكات النحل العضوي",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل العضوي، يتميز بجودة عالية وطعم رائع.",
        price: 53,
        oldPrice: 92,
        category: "sider",
        image: "images/product-10.jpg",
        rating: 4.0,
        stock: 96,
        badge: 'مميز'
    },
    {
        id: 33,
        name: "عسل الزهور الصحي",
        description: "وصف توضيحي للمنتج عسل الزهور الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 87,
        oldPrice: 125,
        category: "flowers",
        image: "images/product-11.jpg",
        rating: 4.6,
        stock: 85,
        badge: 'عرض'
    },
    {
        id: 34,
        name: "عسل السدر الفاخر",
        description: "وصف توضيحي للمنتج عسل السدر الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 157,
        oldPrice: 254,
        category: "clover",
        image: "images/product-1.jpg",
        rating: 4.6,
        stock: 81,
        badge: 'عرض'
    },
    {
        id: 35,
        name: "عسل السمر المميز",
        description: "وصف توضيحي للمنتج عسل السمر المميز، يتميز بجودة عالية وطعم رائع.",
        price: 228,
        oldPrice: null,
        category: "sider",
        image: "images/product-2.jpg",
        rating: 3.9,
        stock: 9,
        badge: 'مميز'
    },
    {
        id: 36,
        name: "شمع العسل النقي",
        description: "وصف توضيحي للمنتج شمع العسل النقي، يتميز بجودة عالية وطعم رائع.",
        price: 70,
        oldPrice: null,
        category: "sider",
        image: "images/product-3.jpg",
        rating: 4.9,
        stock: 23,
        badge: 'مميز'
    },
    {
        id: 37,
        name: "عسل السمر النادر",
        description: "وصف توضيحي للمنتج عسل السمر النادر، يتميز بجودة عالية وطعم رائع.",
        price: 281,
        oldPrice: null,
        category: "sider",
        image: "images/product-4.jpg",
        rating: 3.9,
        stock: 28,
        badge: 'عرض'
    },
    {
        id: 38,
        name: "غذاء ملكات النحل الأصلي",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل الأصلي، يتميز بجودة عالية وطعم رائع.",
        price: 481,
        oldPrice: null,
        category: "gifts",
        image: "images/product-5.jpg",
        rating: 4.1,
        stock: 55,
        badge: 'جديد'
    },
    {
        id: 39,
        name: "عسل الطلح النقي",
        description: "وصف توضيحي للمنتج عسل الطلح النقي، يتميز بجودة عالية وطعم رائع.",
        price: 359,
        oldPrice: 430,
        category: "gifts",
        image: "images/product-6.jpg",
        rating: 4.5,
        stock: 12,
        badge: 'جديد'
    },
    {
        id: 40,
        name: "عسل الحمضيات الأصلي",
        description: "وصف توضيحي للمنتج عسل الحمضيات الأصلي، يتميز بجودة عالية وطعم رائع.",
        price: 268,
        oldPrice: 342,
        category: "clover",
        image: "images/product-7.jpg",
        rating: 3.5,
        stock: 2,
        badge: null
    },
    {
        id: 41,
        name: "عسل السمر العضوي",
        description: "وصف توضيحي للمنتج عسل السمر العضوي، يتميز بجودة عالية وطعم رائع.",
        price: 247,
        oldPrice: null,
        category: "flowers",
        image: "images/product-8.jpg",
        rating: 4.9,
        stock: 72,
        badge: 'جديد'
    },
    {
        id: 42,
        name: "عسل الزهور الجبلي",
        description: "وصف توضيحي للمنتج عسل الزهور الجبلي، يتميز بجودة عالية وطعم رائع.",
        price: 200,
        oldPrice: null,
        category: "clover",
        image: "images/product-9.jpg",
        rating: 4.6,
        stock: 73,
        badge: 'جديد'
    },
    {
        id: 43,
        name: "عسل الحمضيات الفاخر",
        description: "وصف توضيحي للمنتج عسل الحمضيات الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 312,
        oldPrice: 380,
        category: "flowers",
        image: "images/product-10.jpg",
        rating: 4.6,
        stock: 89,
        badge: 'مميز'
    },
    {
        id: 44,
        name: "غذاء ملكات النحل الصحي",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 383,
        oldPrice: 405,
        category: "sider",
        image: "images/product-11.jpg",
        rating: 3.6,
        stock: 33,
        badge: 'مميز'
    },
    {
        id: 45,
        name: "عسل السمر الصحي",
        description: "وصف توضيحي للمنتج عسل السمر الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 450,
        oldPrice: 543,
        category: "sider",
        image: "images/product-1.jpg",
        rating: 4.2,
        stock: 70,
        badge: 'جديد'
    },
    {
        id: 46,
        name: "عسل البرسيم الفاخر",
        description: "وصف توضيحي للمنتج عسل البرسيم الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 479,
        oldPrice: null,
        category: "manuka",
        image: "images/product-2.jpg",
        rating: 3.7,
        stock: 98,
        badge: 'مميز'
    },
    {
        id: 47,
        name: "عسل البرسيم العضوي",
        description: "وصف توضيحي للمنتج عسل البرسيم العضوي، يتميز بجودة عالية وطعم رائع.",
        price: 86,
        oldPrice: 154,
        category: "sider",
        image: "images/product-3.jpg",
        rating: 4.4,
        stock: 67,
        badge: 'عرض'
    },
    {
        id: 48,
        name: "عسل السدر البري",
        description: "وصف توضيحي للمنتج عسل السدر البري، يتميز بجودة عالية وطعم رائع.",
        price: 500,
        oldPrice: 586,
        category: "clover",
        image: "images/product-4.jpg",
        rating: 3.9,
        stock: 68,
        badge: null
    },
    {
        id: 49,
        name: "غذاء ملكات النحل النقي",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل النقي، يتميز بجودة عالية وطعم رائع.",
        price: 189,
        oldPrice: null,
        category: "manuka",
        image: "images/product-5.jpg",
        rating: 4.8,
        stock: 99,
        badge: null
    },
    {
        id: 50,
        name: "شمع العسل النادر",
        description: "وصف توضيحي للمنتج شمع العسل النادر، يتميز بجودة عالية وطعم رائع.",
        price: 324,
        oldPrice: 396,
        category: "clover",
        image: "images/product-6.jpg",
        rating: 4.5,
        stock: 64,
        badge: 'جديد'
    },
    {
        id: 51,
        name: "شمع العسل البري",
        description: "وصف توضيحي للمنتج شمع العسل البري، يتميز بجودة عالية وطعم رائع.",
        price: 470,
        oldPrice: 558,
        category: "flowers",
        image: "images/product-7.jpg",
        rating: 3.9,
        stock: 71,
        badge: null
    },
    {
        id: 52,
        name: "عسل الطلح الفاخر",
        description: "وصف توضيحي للمنتج عسل الطلح الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 169,
        oldPrice: 216,
        category: "flowers",
        image: "images/product-8.jpg",
        rating: 4.9,
        stock: 11,
        badge: null
    },
    {
        id: 53,
        name: "عسل البرسيم الصحي",
        description: "وصف توضيحي للمنتج عسل البرسيم الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 65,
        oldPrice: null,
        category: "clover",
        image: "images/product-9.jpg",
        rating: 4.4,
        stock: 5,
        badge: 'جديد'
    },
    {
        id: 54,
        name: "عسل السمر المميز",
        description: "وصف توضيحي للمنتج عسل السمر المميز، يتميز بجودة عالية وطعم رائع.",
        price: 305,
        oldPrice: null,
        category: "flowers",
        image: "images/product-10.jpg",
        rating: 4.6,
        stock: 6,
        badge: 'جديد'
    },
    {
        id: 55,
        name: "عسل الزهور الفاخر",
        description: "وصف توضيحي للمنتج عسل الزهور الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 171,
        oldPrice: 199,
        category: "flowers",
        image: "images/product-11.jpg",
        rating: 3.6,
        stock: 39,
        badge: null
    },
    {
        id: 56,
        name: "عسل الحمضيات الفاخر",
        description: "وصف توضيحي للمنتج عسل الحمضيات الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 315,
        oldPrice: 336,
        category: "manuka",
        image: "images/product-1.jpg",
        rating: 4.1,
        stock: 61,
        badge: null
    },
    {
        id: 57,
        name: "عسل الكينا الجبلي",
        description: "وصف توضيحي للمنتج عسل الكينا الجبلي، يتميز بجودة عالية وطعم رائع.",
        price: 70,
        oldPrice: 113,
        category: "clover",
        image: "images/product-2.jpg",
        rating: 3.9,
        stock: 47,
        badge: 'مميز'
    },
    {
        id: 58,
        name: "عسل السدر المميز",
        description: "وصف توضيحي للمنتج عسل السدر المميز، يتميز بجودة عالية وطعم رائع.",
        price: 445,
        oldPrice: 529,
        category: "clover",
        image: "images/product-3.jpg",
        rating: 4.1,
        stock: 94,
        badge: 'عرض'
    },
    {
        id: 59,
        name: "عسل المانوكا الصحي",
        description: "وصف توضيحي للمنتج عسل المانوكا الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 58,
        oldPrice: 140,
        category: "gifts",
        image: "images/product-4.jpg",
        rating: 4.8,
        stock: 7,
        badge: 'جديد'
    },
    {
        id: 60,
        name: "عسل الحمضيات البري",
        description: "وصف توضيحي للمنتج عسل الحمضيات البري، يتميز بجودة عالية وطعم رائع.",
        price: 478,
        oldPrice: null,
        category: "manuka",
        image: "images/product-5.jpg",
        rating: 3.9,
        stock: 1,
        badge: 'مميز'
    },
    {
        id: 61,
        name: "عسل السدر النادر",
        description: "وصف توضيحي للمنتج عسل السدر النادر، يتميز بجودة عالية وطعم رائع.",
        price: 481,
        oldPrice: 504,
        category: "gifts",
        image: "images/product-6.jpg",
        rating: 4.6,
        stock: 24,
        badge: null
    },
    {
        id: 62,
        name: "عسل الكينا الجبلي",
        description: "وصف توضيحي للمنتج عسل الكينا الجبلي، يتميز بجودة عالية وطعم رائع.",
        price: 410,
        oldPrice: 460,
        category: "manuka",
        image: "images/product-7.jpg",
        rating: 5.0,
        stock: 22,
        badge: null
    },
    {
        id: 63,
        name: "عسل السدر النادر",
        description: "وصف توضيحي للمنتج عسل السدر النادر، يتميز بجودة عالية وطعم رائع.",
        price: 454,
        oldPrice: null,
        category: "clover",
        image: "images/product-8.jpg",
        rating: 4.6,
        stock: 53,
        badge: null
    },
    {
        id: 64,
        name: "عسل الحمضيات الصحي",
        description: "وصف توضيحي للمنتج عسل الحمضيات الصحي، يتميز بجودة عالية وطعم رائع.",
        price: 444,
        oldPrice: 530,
        category: "clover",
        image: "images/product-9.jpg",
        rating: 4.2,
        stock: 39,
        badge: 'مميز'
    },
    {
        id: 65,
        name: "عسل الزهور الملكي",
        description: "وصف توضيحي للمنتج عسل الزهور الملكي، يتميز بجودة عالية وطعم رائع.",
        price: 350,
        oldPrice: 450,
        category: "clover",
        image: "images/product-10.jpg",
        rating: 4.0,
        stock: 2,
        badge: 'عرض'
    },
    {
        id: 66,
        name: "غذاء ملكات النحل الجبلي",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل الجبلي، يتميز بجودة عالية وطعم رائع.",
        price: 431,
        oldPrice: 496,
        category: "gifts",
        image: "images/product-11.jpg",
        rating: 4.6,
        stock: 99,
        badge: null
    },
    {
        id: 67,
        name: "شمع العسل النادر",
        description: "وصف توضيحي للمنتج شمع العسل النادر، يتميز بجودة عالية وطعم رائع.",
        price: 263,
        oldPrice: null,
        category: "gifts",
        image: "images/product-1.jpg",
        rating: 3.5,
        stock: 74,
        badge: 'مميز'
    },
    {
        id: 68,
        name: "غذاء ملكات النحل البري",
        description: "وصف توضيحي للمنتج غذاء ملكات النحل البري، يتميز بجودة عالية وطعم رائع.",
        price: 353,
        oldPrice: null,
        category: "flowers",
        image: "images/product-2.jpg",
        rating: 4.9,
        stock: 22,
        badge: 'عرض'
    },
    {
        id: 69,
        name: "عسل الطلح الفاخر",
        description: "وصف توضيحي للمنتج عسل الطلح الفاخر، يتميز بجودة عالية وطعم رائع.",
        price: 218,
        oldPrice: 314,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 3.9,
        stock: 69,
        badge: 'عرض'
    },
    {
        id: 70,
        name: "شمع العسل العضوي",
        description: "وصف توضيحي للمنتج شمع العسل العضوي، يتميز بجودة عالية وطعم رائع.",
        price: 151,
        oldPrice: null,
        category: "sider",
        image: "images/product-4.jpg",
        rating: 4.4,
        stock: 5,
        badge: 'جديد'
    },
    {
        id: 71,
        name: "عسل الحمضيات المميز",
        description: "يتميز بنكهة فريدة ورائحة زكية، يعتبر خياراً مثالياً للهدايا.",
        price: 306,
        category: "flowers",
        image: "images/product-5.jpg",
        rating: 4.3,
        stock: 17,
    },
    {
        id: 72,
        name: "عسل الحمضيات النقي",
        description: "عسل طبيعي 100% يتميز بطعمه الغني وفوائده الصحية المتعددة.",
        price: 120,
        oldPrice: 168,
        category: "flowers",
        image: "images/product-6.jpg",
        rating: 4.9,
        stock: 48,
    },
    {
        id: 73,
        name: "عسل المانوكا النقي",
        description: "عسل فاخر ذو قوام كثيف وطعم لا يقاوم، مثالي للاستخدام اليومي.",
        price: 165,
        category: "manuka",
        image: "images/product-7.jpg",
        rating: 4.8,
        stock: 17,
    },
    {
        id: 74,
        name: "عسل المانوكا العضوي",
        description: "يتميز بنكهة فريدة ورائحة زكية، يعتبر خياراً مثالياً للهدايا.",
        price: 349,
        oldPrice: 372,
        category: "manuka",
        image: "images/product-8.jpg",
        rating: 4.5,
        stock: 40,
        badge: "جديد",
    },
    {
        id: 75,
        name: "عسل الزهور الملكي",
        description: "من أجود أنواع العسل، تم استخلاصه بعناية فائقة لضمان الجودة.",
        price: 111,
        oldPrice: 144,
        category: "flowers",
        image: "images/product-9.jpg",
        rating: 5.0,
        stock: 15,
        badge: "جديد",
    },
    {
        id: 76,
        name: "عسل الزهور الفاخر",
        description: "عسل طبيعي 100% يتميز بطعمه الغني وفوائده الصحية المتعددة.",
        price: 293,
        category: "flowers",
        image: "images/product-10.jpg",
        rating: 3.8,
        stock: 4,
    },
    {
        id: 77,
        name: "عسل المانوكا الجبلي",
        description: "من أجود أنواع العسل، تم استخلاصه بعناية فائقة لضمان الجودة.",
        price: 262,
        oldPrice: 328,
        category: "manuka",
        image: "images/product-11.jpg",
        rating: 4.6,
        stock: 32,
    },
    {
        id: 78,
        name: "عسل السمر الفاخر",
        description: "يتميز بنكهة فريدة ورائحة زكية، يعتبر خياراً مثالياً للهدايا.",
        price: 375,
        oldPrice: 468,
        category: "sider",
        image: "images/product-1.jpg",
        rating: 4.5,
        stock: 49,
        badge: "جديد",
    },
    {
        id: 79,
        name: "عسل الكينا البري",
        description: "عسل فاخر ذو قوام كثيف وطعم لا يقاوم، مثالي للاستخدام اليومي.",
        price: 175,
        category: "flowers",
        image: "images/product-2.jpg",
        rating: 3.9,
        stock: 1,
        badge: "عرض خاص",
    },
    {
        id: 80,
        name: "عسل الكينا البري",
        description: "عسل طبيعي 100% يتميز بطعمه الغني وفوائده الصحية المتعددة.",
        price: 122,
        category: "flowers",
        image: "images/product-3.jpg",
        rating: 4.2,
        stock: 25,
    }
];
